name: run dbt Cloud job on push
on:
  push:
    branches:
      - 'main'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /workspace/dbt_core_container/dbt_learn
          git clean -f
          git checkout main
          git fetch
          git pull origin main
          dbt deps
          dbt seed
          dbt run

